---
driver:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /lib/systemd/systemd

transport:
  name: sftp

platforms:
  - name: ubuntu-1804-2019-2-py3
    driver:
      image: netmanagers/salt-2019.2-py3:ubuntu-18.04

provisioner:
  name: salt_solo
  log_level: debug
  require_chef: true
  salt_copy_filter:
    - .kitchen
    - .git
  pillars-from-files:
    data.sls: test/pillar/data.sls
  formula: envoy
  state_top:
    base:
      '*':
        - envoy
  pillars:
    top.sls:
      base:
        "*":
          - data

suites:
  - name: fluorine
    provisioner:
      salt_bootstrap_options: -X -p git stable 2019.2
  #- name: nitrogen
  #  provisioner:
  #    salt_bootstrap_options: -X -p git stable 2017.7
  #- name: carbon
  #  provisioner:
  #    salt_bootstrap_options: -X -p git stable 2016.11

verifier:
  name: shell
  remote_exec: false
  command: >
    pytest -vvv --spec
    --connection=docker
    --hosts=root@$KITCHEN_CONTAINER_ID
    --junit-xml junit-$KITCHEN_INSTANCE.xml
    test/acceptance/test_envoy.py
