---
driver:
  name: docker
  use_sudo: false
  privileged: true

transport:
  name: sftp

platforms:
  - name: ubuntu-16.04
    driver_config:
      run_command: /usr/lib/systemd/systemd
  - name: ubuntu-18.04
    driver_config:
      run_command: /usr/lib/systemd/systemd

provisioner:
  name: salt_solo
  require_chef: true
  pillars-from-files:
    envoy.sls: test/pillar/envoy.sls
  formula: envoy
  state_top:
    base:
      '*':
        - envoy
  pillars:
    top.sls:
      base:
        "*":
          - envoy

suites:
  - name: nitrogen
    provisioner:
      salt_bootstrap_options: -X -p git stable 2017.7
  - name: carbon
    provisioner:
      salt_bootstrap_options: -X -p git stable 2016.11

verifier:
  name: shell
  remote_exec: false
  command: >
    py.test -vvv
    --connection=docker
    --hosts=root@$KITCHEN_CONTAINER_ID
    --junit-xml junit-$KITCHEN_INSTANCE.xml
    test/integration/$KITCHEN_SUITE
