# -*- coding: utf-8 -*-
# vim: ft=yaml
---
## Machine config
dist: bionic
sudo: required
services:
  - docker

## Language and cache config
language: ruby
cache: bundler

## Script to run for the test stage
script:
  - bin/kitchen list
  - bundle install
  - bundle exec kitchen test
  - bin/kitchen verify "${INSTANCE}"

## Stages and jobs matrix
stages:
  - test
  - name: release
    if: branch = master AND type != pull_request
jobs:
  include:
    ## Define the test stage that runs the linters
    # Run all of the linters in a single job
    - language: node_js
      node_js: lts/*
      env: Lint
      name: 'Lint: salt-lint, yamllint'
      before_install: skip
      script:
        # Install and run `salt-lint`
        - pip install --user salt-lint
        - git ls-files | grep '\.sls$\|\.jinja$\|\.j2$\|\.tmpl$'
                       | xargs -I {} salt-lint {}
        # Install and run `yamllint`
        # Need at least `v1.17.0` for the `yaml-files` setting
        - pip install --user yamllint>=1.17.0
        - yamllint -s .

    ## Define the rest of the matrix based on Kitchen testing
    # Make sure the instances listed below match up with
    # the `platforms` defined in `kitchen.yml`
    # - env: INSTANCE=default-debian-10-master-py3
    # - env: INSTANCE=default-ubuntu-1804-develop-py3
    # - env: INSTANCE=default-centos-7-develop-py3
    # - env: INSTANCE=default-fedora-30-develop-py3
    # - env: INSTANCE=default-opensuse-leap-15-develop-py3
    # - env: INSTANCE=default-amazonlinux-2-develop-py2
    # - env: INSTANCE=default-arch-base-latest-develop-py2
    # - env: INSTANCE=default-debian-9-2019-2-py3
    - env: INSTANCE=default-ubuntu-1804-2019-2-py3
    # - env: INSTANCE=default-centos-7-2019-2-py3
    # - env: INSTANCE=default-fedora-30-2019-2-py3
    # - env: INSTANCE=default-opensuse-leap-15-2019-2-py3
    # - env: INSTANCE=default-amazonlinux-2-2019-2-py2
    # - env: INSTANCE=default-arch-base-latest-2019-2-py2
    # - env: INSTANCE=default-debian-9-2018-3-py2
    # - env: INSTANCE=default-ubuntu-1604-2018-3-py2
    # - env: INSTANCE=default-centos-7-2018-3-py2
    # - env: INSTANCE=default-fedora-29-2018-3-py2
    # - env: INSTANCE=default-opensuse-leap-15-2018-3-py2
    # - env: INSTANCE=default-amazonlinux-2-2018-3-py2
    # - env: INSTANCE=default-arch-base-latest-2018-3-py2
    # - env: INSTANCE=default-debian-8-2017-7-py2
    # - env: INSTANCE=default-ubuntu-1604-2017-7-py2
    # - env: INSTANCE=centos6-centos-6-2017-7-py2
    # - env: INSTANCE=default-fedora-29-2017-7-py2
    # - env: INSTANCE=default-opensuse-leap-15-2017-7-py2
    # - env: INSTANCE=default-amazonlinux-2-2017-7-py2
    # - env: INSTANCE=default-arch-base-latest-2017-7-py2
